version: '3.8'

services:
  web:
    build: .
    command: /env/bin/python -m gunicorn --bind 0.0.0.0:8001 --workers 3 SupnumGradingAi.wsgi:application
    volumes:
      - .:/app
    ports:
      - "8001:8001"
